services:
  api:
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      - IS_DEVELOPMENT=true
      - LOG_LEVEL=DEBUG
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
