"""
app/db/models/audit_log.py - Domain and database models for the audit log.

The audit log is an immutable, append-only record of sensitive actions.
No updates or deletes are ever performed on this table.
"""
from datetime import datetime
from typing import Any, Optional

from pydantic import BaseModel, ConfigDict, Field


class AuditLog(BaseModel):
    """
    Domain model for an audit log entry.

    Written by AuditLogger service for every sensitive action (billing entry
    created/edited/deleted, bill sent, fee agreement signed, billing cycle
    closed, user role changed, trust ledger transaction posted).

    ``entity_id`` is stored as a string to accommodate both integer PKs and
    UUID PKs without schema changes.
    """
    supabase_uid: Optional[str] = Field(
        default=None,
        description="Supabase Auth UID of the user who performed the action; null for system actions",
    )
    action: str = Field(
        ...,
        description="Dot-namespaced action identifier, e.g. 'billing_entry.created'",
    )
    entity_type: str = Field(
        ...,
        description="Type of entity affected, e.g. 'billing_entry', 'fee_agreement'",
    )
    entity_id: Optional[str] = Field(
        default=None,
        description="String representation of the primary key of the affected record",
    )
    before_json: Optional[dict[str, Any]] = Field(
        default=None,
        description="Snapshot of the record state before the action; null for create actions",
    )
    after_json: Optional[dict[str, Any]] = Field(
        default=None,
        description="Snapshot of the record state after the action; null for delete actions",
    )


class AuditLogInDB(AuditLog):
    """
    Database model — extends AuditLog with DB-managed metadata.

    The ``id`` is a UUID string (gen_random_uuid() in Postgres) to ensure
    global uniqueness across shards and prevent sequential enumeration.
    """
    id: str = Field(..., description="UUID primary key, generated by the database")
    created_at: datetime = Field(..., description="Timestamp the audit event was written, set by the database")
    # Audit log entries are immutable — no updated_at
    model_config = ConfigDict(from_attributes=True)
